version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABASE: data-client
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_TTL: 20
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: data-client

  redis:
    image: redis:latest
    ports:
      - "6379:6379"